### ISSUE TITLE
[Deploy]

### ISSUE THREAD

**Issue by nyeonkim91** [politicat/politicat#24]
-Digital Ocean

**Comment by nyeonkim91** [comment]
- we cannot crawl the data because of the lack of memory

**Comment by MJ111** [comment]
crontab reference:
http://www.cyberciti.biz/faq/show-all-running-processes-in-linux/
https://haandol.wordpress.com/2013/08/23/grep%EC%9C%BC%EB%A1%9C-pid-%EC%B0%BE%EC%95%84%EB%82%B4%EC%84%9C-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EC%82%AD%EC%A0%9C%ED%95%98%EA%B8%B0%EB%A5%BC-%EC%89%98-%EB%AA%85%EB%A0%B9-%ED%95%9C%EC%A4%84/
http://stackoverflow.com/questions/2366693/run-cron-job-only-if-it-isnt-already-running

#cron_nlp.sh
#!/bin/sh
if ps -ef | grep -v grep | grep NlpTitles.py; then
        kill $(ps -ef | grep -v grep | grep NlpTitles.py |awk '{print $2}')
fi

/usr/bin/python3 /var/www/politicat.com/nlp/NlpTitles.py >> /var/www/politicat.com/cron_nlp.log &

exit 0
